//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastCare.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_estoque
    {
        public int id_estoque { get; set; }
        public int id_suprimento { get; set; }
        public Nullable<int> qt_produtos { get; set; }
    
        public virtual tb_suprimento tb_suprimento { get; set; }
    }
}
