//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastCare.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_fornecedor()
        {
            this.tb_suprimento = new HashSet<tb_suprimento>();
        }
    
        public int id_fornecedor { get; set; }
        public string nm_forn { get; set; }
        public string ds_cep { get; set; }
        public string end_forn { get; set; }
        public string nu_forn { get; set; }
        public string ds_tel { get; set; }
        public string ds_cel { get; set; }
        public string ds_email { get; set; }
        public string ds_cnpj { get; set; }
        public string ds_cpf { get; set; }
        public string uf_estado { get; set; }
        public string insc_estadual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_suprimento> tb_suprimento { get; set; }
    }
}
