//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastCare.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_funcionario()
        {
            this.tb_car_ponto = new HashSet<tb_car_ponto>();
            this.tb_pagamento = new HashSet<tb_pagamento>();
        }
    
        public int id_funcionario { get; set; }
        public string nm_funcionario { get; set; }
        public System.DateTime dt_nasc { get; set; }
        public string ds_rg { get; set; }
        public string ds_cpf { get; set; }
        public string end_funcionario { get; set; }
        public string nu_funcionario { get; set; }
        public string ds_cep { get; set; }
        public string ds_tel { get; set; }
        public string ds_cel { get; set; }
        public string ds_email { get; set; }
        public string nm_cargo { get; set; }
        public decimal qt_salario { get; set; }
        public string ds_setor { get; set; }
        public System.DateTime dt_contratacao { get; set; }
        public string ds_genero { get; set; }
        public string uf_estado { get; set; }
        public string est_civil { get; set; }
        public Nullable<bool> bl_vt { get; set; }
        public Nullable<decimal> vl_vt { get; set; }
        public Nullable<bool> bl_va { get; set; }
        public Nullable<decimal> vl_va { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_car_ponto> tb_car_ponto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pagamento> tb_pagamento { get; set; }
    }
}
