//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastCare.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_login
    {
        public int id_login { get; set; }
        public string nm_email { get; set; }
        public string nm_usuario { get; set; }
        public string ds_senha { get; set; }
        public string ds_tipo { get; set; }
        public byte[] img_usuario { get; set; }
    }
}
