//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastCare.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pagamento
    {
        public int id_pagamento { get; set; }
        public int id_funcionario { get; set; }
        public string nm_funcionario { get; set; }
        public string função { get; set; }
        public Nullable<System.DateTime> dt_mes { get; set; }
        public Nullable<decimal> salario { get; set; }
        public Nullable<decimal> salario_base { get; set; }
        public Nullable<decimal> INSS { get; set; }
        public Nullable<decimal> FGTS { get; set; }
        public Nullable<decimal> VA { get; set; }
        public Nullable<decimal> VT { get; set; }
        public Nullable<int> nu_falta { get; set; }
        public Nullable<decimal> desc_falta { get; set; }
        public Nullable<decimal> total_desconto { get; set; }
        public Nullable<decimal> valor_liquido { get; set; }
        public Nullable<int> horasextra { get; set; }
        public Nullable<decimal> horaextraareceber { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
